src/paulscode/android/mupen64plusae/persistent/GamePrefs.java

The auto-hold values were loaded using the wrong tag name when it came time to play the game, so auto-hold never worked. This just fixes the tag name.

Fixed auto-hold for touchscreen controls

---

src/paulscode/android/mupen64plusae/input/map/TouchMap.java
src/paulscode/android/mupen64plusae/profile/TouchscreenProfileActivity.java

Things that are changed with this commit:
- added drag and drop editing for the on-screen controller layout.
Right now the values are clamped to the nearest 5% to match the
behavior of the edit dialog, although I feel like we should allow any %
for that.
- tapping on a button plays the standard button sound effect, as I felt
that was missing.
- made it possible to swipe from the top or bottom of the screen to
show the back/home/menu buttons or status bar without *also* triggering
the edit dialog for a button that was under your finger, since that
dialog prevented the user from being able to use the menus at the top
of the screen.

Drag and drop editing for the touchscreen controls

---

src/paulscode/android/mupen64plusae/persistent/GamePrefs.java

Currently, if one loads a game without first going to the GamePrefsActivity at least once for a specific game. The game will not load the correct default profile. This fixes that.

Load the correct default profile if we have not yet visited the  GamePrefsActivity for a game.

---

src/paulscode/android/mupen64plusae/CacheRomInfoFragment.java
src/paulscode/android/mupen64plusae/GalleryActivity.java
src/paulscode/android/mupen64plusae/ScanRomsActivity.java
src/paulscode/android/mupen64plusae/persistent/GlobalPrefs.java
src/paulscode/android/mupen64plusae/task/CacheRomInfoService.java
src/paulscode/android/mupen64plusae/util/RomDatabase.java

Fixed crash if application is killed by os while the ScanRomActivity is active.
Fixed issue that could cause the service notification icon to remain if the application was killed by the OS.
Fixed issue that prevented some gallery cover art from downloading correctly.
Fixed issue with scan config parameters not being passed on to the scan service.

Directory selection activity fixes

---

src/paulscode/android/mupen64plusae/game/GameActivity.java
src/paulscode/android/mupen64plusae/game/GameActivityXperiaPlay.java

This fixes issues with the volume key not working during game to adjust media volume for some devices.
See issue: #455

Volume button during gameplay fix

---

res/xml/preferences_global.xml

Removed these general options: search zips, download art, and clear gallery. They are now set on the directory selection activity before each ROM scan.

Removed unneeded general options

---

src/paulscode/android/mupen64plusae/GalleryItem.java
src/paulscode/android/mupen64plusae/task/LoadBitmapTask.java

Fix GalleryActivity jerkyness by loading bitmaps in a background task.

---

src/paulscode/android/mupen64plusae/persistent/GamePrefs.java

Fixed issue where if a game's configured profile doesn't exist in the list of user profiles, the app would crash.

Fixed crash when loading unknown profile

---

src/paulscode/android/mupen64plusae/cheat/CheatEditorActivity.java

Adding, editing, and deleting cheats no longer re-creates the whole list adapter in the CheatEditorActivity. This means that the scroll position is no longer reset.

Adding, editing, and deleting no longer resets scroll position

---

res/values/strings.xml
src/paulscode/android/mupen64plusae/persistent/GamePrefs.java
src/paulscode/android/mupen64plusae/persistent/GamePrefsActivity.java
src/paulscode/android/mupen64plusae/preference/ProfilePreference.java
src/paulscode/android/mupen64plusae/profile/ManageProfilesActivity.java

* Did some refactoring so that some preference strings are no longer manually typed in more than one class.
* Now search for the default profile correctly if a controller profile is not found
* Renamed "Current Default" profile to "Global Default"
* Allow the "Global Default" profile to use the "Disabled" profile.
* The currently selected profile for a game can now be viewed without having to click on the option to set the profile.
* Several improvements to the ManageProfilesActivity

Additional profile fixes

---

res/menu/game_drawer.xml
src/paulscode/android/mupen64plusae/GalleryActivity.java
src/paulscode/android/mupen64plusae/game/GameActivity.java
src/paulscode/android/mupen64plusae/game/GameActivityXperiaPlay.java
src/paulscode/android/mupen64plusae/game/GameLifecycleHandler.java
src/paulscode/android/mupen64plusae/game/GameSurface.java
src/paulscode/android/mupen64plusae/input/PeripheralController.java
src/paulscode/android/mupen64plusae/jni/CoreInterface.java

* Gameplay will be restored automatically and the sidebar closed if a slot or file is loaded or saved. This involved fixing a lot of corner cases.
* The gallery game side bar is now closed automatically when launching a game. This forces a refresh of the gallery sidebar so the the resume button shows up when a game is opened for the first time.
* Now no longer showing the toast staying that a game is being resumed when a game is being restarted. This is done correctly this time.
* We will now no longer exit the GameActivity immediately after a user chooses to exit. We will now wait until the core is done fully shutting down.
* Added a reset option to the in-game sidebar.

Mupen64plus core interaction enhancements and UI enhancements

---

res/values/strings.xml
src/paulscode/android/mupen64plusae/game/GameActivity.java
src/paulscode/android/mupen64plusae/input/map/PlayerMap.java
src/paulscode/android/mupen64plusae/input/provider/AbstractProvider.java

This commit will allow mapped controllers to be remembered by their device "descriptor" rather than the device id. This will allow controllers that have been disconnected and reconnected to be automatically remapped when one of the buttons is pressed. Also, deserialization should be compatible with current saved controller settings.
Note that in-game controller processing still uses the device ids for performance reasons. Also note that pre-Jelly Bean devices must still use device ids, and I was unable to test this with my setup.

Allow mapped controllers to automatically reconnect.

---

AndroidManifest.xml
jni/ae-bridge/ae_exports.cpp
jni/mupen64plus-core.mk
src/paulscode/android/mupen64plusae/jni/CoreInterface.java
src/paulscode/android/mupen64plusae/jni/NativeExports.java
src/paulscode/android/mupen64plusae/persistent/AppData.java

Builds 2 shared objects for the core on x86 and switches between them at run-time depending on if Android M or later is detected. This fixes https://github.com/mupen64plus-ae/mupen64plus-ae/issues/540. Known Issue: Cannot resume a game when the PIC-compliant version of the core (old dynamic recompiler) is loaded.

Fixed text relocation errors on x86 Android M

---

src/paulscode/android/mupen64plusae/jni/CoreInterface.java
src/paulscode/android/mupen64plusae/persistent/AppData.java

I discovered that the old dynamic recompiler (for x86 on Marshmallow and newer) apparently needs a little bit of warm-up time before it can load saves. I tested this on my Nexus Player to determine how long of a warm-up was needed. It was somewhere between 250ms and 500ms, so I doubled that to 1000ms. It still may not work every time on everyone's setup, but I haven't been able to get it to fail. Hopefully, this is only a temporary fix until the new dynamic recompiler can support Marshmallow on x86.

Hack to temporarily fix issues with resuming on x86 Marshmallow.

---

app/src/main/assets/mupen64plus_data/profiles/controller.cfg
app/src/main/java/paulscode/android/mupen64plusae/task/ExtractAssetsTask.java

The raphnet-tech GC/N64 and N64 to USB adapters do not work
with the built-in profile, or at least not on all systems.
This patch adds a new built-in profile that works out of the box
with raphnet v3 adapters. Tested on a Samsum SM-J320V running android
7.1.1.

Add a built-in profile for raphnet-tech GC/N64 to USB V3

---

mupen64plus-video-glide64mk2/upstream/src/Glitch64/glitchmain.h

https://github.com/mupen64plus/mupen64plus-video-glide64mk2/commit/3f76408

video-glide64mk2: Update to commit 3f76408.

---

mupen64plus-video-rice/upstream/src/osal_opengl.h

https://github.com/mupen64plus/mupen64plus-video-rice/commit/677257a

video-rice: Update to commit 677257a.

---

.github/workflows/continuous-integration-workflow.yml
README.md

Hi there, this PR adds the following:
- I changed the Github Workflow so it will upload the Debug and Release APK's.
- Changes the README.md and points to Nightly Builds by clicking on "Mupen64Plus-AE - Passing" people can go to the CI/CD builds, and go to Artifacts to download the "apk" file.
There is a build running at this moment, when it completes you can see the "apk" file on the following Github page:
https://github.com/bladeoner/mupen64plus-ae/actions/runs/285936173
And the changes I made to the README.md you can see it under my branch:
https://github.com/bladeoner/mupen64plus-ae/tree/artifacts

Add uploading build artifacts

---

.github/workflows/continuous-integration-workflow.yml

This will only upload the debug artifacts because the release artifacts won't work unsigned.

Only upload debug artifacts

---

app/src/main/java/paulscode/android/mupen64plusae/game/GameActivity.java

getDefaultSharedPreferences was causing a null exception in GameActivity.java.

Fix - Fire TV Cube - crash on load

---

app/src/main/AndroidManifest.xml

Android 7.0 use the scheme "content" with the mimeType "*/*" without the line <data android:scheme="content" /> on Android 7.0 the mimeType was ignored and causing File Explorer like ES File Explorer to not allow to open file using Mupen.
With the change, we can now open n64, v64, z64, zip, 7z. 7zip from a File Explorer .i.e. ( ES File Explorer ).
From official Android 7.0 Changes:
For apps targeting Android 7.0, the Android framework enforces the StrictMode API policy that prohibits exposing file:// URIs outside your app. If an intent containing a file URI leaves your app, the app fails with a FileUriExposedException exception.
To share files between applications, you should send a content:// URI and grant a temporary access permission on the URI. The easiest way to grant this permission …

AndroidManifest - File extension - Missing scheme

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-report.yml
.github/ISSUE_TEMPLATE/question-report.yml

Hi @fzurita I've added a bug, feature request, and question report. This makes it easier for someone to create an issue or feature request and it makes it also easier for you to distinguish.
I created a test repository where you can see how it works, if you go to the following and click on 'New issue' you will see how it will look: https://github.com/bladeoner/repository-to-test/issues
You have three options: Bug Report, Feature request, or Question click on Get Started
Bug report:
You need to fill in a title behind [Issue]:
The following are mandatory: Describe the bug, Steps to reproduce, Expected behavior (you see a red star behind the names).
The other two Relevant log output and Add screenshots are optional.
Feature request:
You need to fill in a title behind [Feature request]: …

Add bug, feature request and question reports

---

mupen64plus-input-android/src/plugin.cpp

This PR will fix #1037. This will avoid possible buffer overflow read on "m64pButtons" array.

Avoid buffer overflow read on 'm64pButtons'

---

.github/workflows/build.yml

Hi @fzurita I hope your are doing well.
In the latest pipeline runs you see an warning about Node.js that is needs to be updated to a higher version.
Warning: _The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-java@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/_
Example pipeline run: https://github.com/mupen64plus-ae/mupen64plus-ae/actions/runs/6845670591
To resolve the warning I have updated the Java action to v3

Update node.js to version 16
