res/values/strings.xml
src/paulscode/android/mupen64plusae/dialog/ProgressDialog.java
src/paulscode/android/mupen64plusae/task/CacheRomInfoTask.java

Updated CacheRomInfoTask to route through the localization system, then translated the strings to the best of my abilities. Also fixed a few errors with some of the files (copy-pasted French translations in non-French titles).

Adding localization support to the ROM scan feature

---

res/layout/gallery_activity.xml
res/layout/list_item_menu.xml
res/menu/gallery_drawer.xml
src/paulscode/android/mupen64plusae/GalleryActivity.java
src/paulscode/android/mupen64plusae/MenuListView.java

@BonzaiThePenguin
Please merge or close at your discretion.  If it makes your subsequent PRs more difficult to arrange, then just close.
No functional changes.  Tends to make diffs easier to read and merges/
cherry-picks go more smoothly.
Eclipse formatter settings in doc/config_files.

cleanup: Auto-format whitespace.

---

res/values/arrays.xml

Fix issue where we are missing an item value in inputMapActivity_values in arrays.xml

Fix issue where we are missing an item value in inputMapActivity_values in arrays.xml

---

jni/mupen64plus-video-gliden64/src/OpenGL.cpp
src/paulscode/android/mupen64plusae/persistent/AppData.java
src/paulscode/android/mupen64plusae/persistent/GlobalPrefs.java

Added code to auto detect android TV

Auto detect android TV and x86 GLideN64 auto exit workaround

---

src/paulscode/android/mupen64plusae/profile/ManageProfilesActivity.java

See this issue:
https://github.com/mupen64plus-ae/mupen64plus-ae/issues/461

Fix issue where deleting the default profile causes crashes.

---

src/paulscode/android/mupen64plusae/dialog/ProgressDialog.java

Fix issue where some text isn't being saved on the rom scan dialog when rotating the screen.

Fix display issue when rotating the screen during rom scan

---

src/paulscode/android/mupen64plusae/CacheRomInfoFragment.java
src/paulscode/android/mupen64plusae/GalleryActivity.java
src/paulscode/android/mupen64plusae/task/CacheRomInfoService.java

This this issue:
https://github.com/mupen64plus-ae/mupen64plus-ae/issues/456

Fix for Rom scan failure on some devices

---

src/paulscode/android/mupen64plusae/CacheRomInfoFragment.java

Fix crash on exit

---

res/menu/game_activity.xml
res/values/strings.xml
src/paulscode/android/mupen64plusae/game/GameAutoSaveManager.java
src/paulscode/android/mupen64plusae/game/GameLifecycleHandler.java
src/paulscode/android/mupen64plusae/game/GameMenuHandler.java
src/paulscode/android/mupen64plusae/jni/CoreInterface.java

Now saving up 10 auto saves using date/time as the file name.
We also allow users loading these from in the in-game menu.

Auto save history

---

res/layout/game_activity.xml
res/values/strings.xml
src/paulscode/android/mupen64plusae/DrawerLayout.java
src/paulscode/android/mupen64plusae/GalleryActivity.java
src/paulscode/android/mupen64plusae/GameActivity.java
src/paulscode/android/mupen64plusae/GameActivityXperiaPlay.java
src/paulscode/android/mupen64plusae/GameLifecycleHandler.java
src/paulscode/android/mupen64plusae/Keys.java
src/paulscode/android/mupen64plusae/PlayMenuActivity.java

The ActionBar during gameplay was replaced with a sidebar. The
ActionBar logic is technically still there, and will need to be removed
once we verify that the sidebar did not cause any major regressions.

Implemented the sidebar during gameplay

---

src/paulscode/android/mupen64plusae/task/CacheRomInfoService.java

Fix issue that allowed any extracted file to be considered a ROM

Fix issue that allowed any extracted file to be considered a ROM

---

src/paulscode/android/mupen64plusae/game/GameSurface.java

Crash on exit fix

---

src/paulscode/android/mupen64plusae/game/GameSurface.java

Cleaner exception printing for the exception when exiting games.

Cleaner exception printing.

---

res/values/strings.xml
res/xml/preferences_global.xml
src/paulscode/android/mupen64plusae/game/GameAutoSaveManager.java
src/paulscode/android/mupen64plusae/game/GameLifecycleHandler.java
src/paulscode/android/mupen64plusae/persistent/GlobalPrefs.java

Added config parameter under general settings for the maximum number of auto saves.
Changed default sidebar opacity to 80%

Added config parameter for auto save number

---

src/paulscode/android/mupen64plusae/cheat/CheatEditorActivity.java
src/paulscode/android/mupen64plusae/persistent/GamePrefsActivity.java

Potentially fixed issue with cheat titles not refreshing.
Now clearing selected cheats if user cheats change.

Cheat title not refreshing

---

res/values/strings.xml
src/paulscode/android/mupen64plusae/persistent/GamePrefs.java
src/paulscode/android/mupen64plusae/preference/ProfilePreference.java
src/paulscode/android/mupen64plusae/profile/ManageProfilesActivity.java
src/paulscode/android/mupen64plusae/profile/Profile.java

Fixed issue that caused the wrong profile to be selected if a custom profile is currently default.
Also, added a "Current Default" profile that will always select the current default
Made this profile the default profile.

Profile improvements

---

src/paulscode/android/mupen64plusae/persistent/GamePrefsActivity.java

Speed up clearing of selected cheats after cheats are modified

Speed up clearing of selected cheats after cheats are modified

---

src/paulscode/android/mupen64plusae/GalleryItem.java
src/paulscode/android/mupen64plusae/task/CacheRomInfoService.java
src/paulscode/android/mupen64plusae/task/LoadBitmapTask.java

Fixed issue where the incorrect gallery art is shown momentarily if scrolling very fast.

Fix incorrect gallery art

---

res/layout/gallery_activity.xml
res/layout/game_activity.xml
res/layout/game_sidebar_header.xml
src/paulscode/android/mupen64plusae/GameSidebar.java
src/paulscode/android/mupen64plusae/game/GameLifecycleHandler.java

The controller now works again to navigate in the side bar during gameplay.

Fixed issues with controller when the sidebar is open in-game

---

project.properties
res/layout/gallery_activity.xml
src/paulscode/android/mupen64plusae/GalleryActivity.java
src/paulscode/android/mupen64plusae/GalleryItem.java
src/paulscode/android/mupen64plusae/GameSidebar.java
src/paulscode/android/mupen64plusae/GridLayoutManagerBetterScrolling.java
src/paulscode/android/mupen64plusae/persistent/GamePrefs.java
src/paulscode/android/mupen64plusae/persistent/GamePrefsActivity.java
tools/auto-build.sh

Now disabling touch screen profiles when a "big screen" is detected. This only affects android TV at this point.
Fixed several scrolling annoyances in the Gallery view and the in-game sidebar.

Additional tv mode improvements

---

src/paulscode/android/mupen64plusae/game/GameActivity.java
src/paulscode/android/mupen64plusae/persistent/AppData.java
src/paulscode/android/mupen64plusae/persistent/GamePrefs.java
src/paulscode/android/mupen64plusae/persistent/GlobalPrefs.java

Fix issues with immersive mode.
Fix issues with stretch mode not working correctly with GLideN64 at native resolution.

Immersive mode issue

---

src/paulscode/android/mupen64plusae/jni/NativeConfigFiles.java
src/paulscode/android/mupen64plusae/persistent/GamePrefs.java
src/paulscode/android/mupen64plusae/persistent/GlobalPrefs.java

Fixed some remaining resolution issues.

front: Fixed resolution issues.

---

src/paulscode/android/mupen64plusae/input/InputEntry.java
src/paulscode/android/mupen64plusae/input/InputStrengthCalculator.java
src/paulscode/android/mupen64plusae/input/PeripheralController.java
src/paulscode/android/mupen64plusae/input/map/InputMap.java
src/paulscode/android/mupen64plusae/profile/ControllerProfileActivityBase.java

This commit allows buttons and axes to map to the same controls.

Removed restrictions on buttons and axes mapping to same control.

---

mupen64plus-rsp-hle/upstream/.travis.yml
mupen64plus-rsp-hle/upstream/RELEASE
mupen64plus-rsp-hle/upstream/projects/VisualStudio2017/mupen64plus-rsp-hle.vcxproj
mupen64plus-rsp-hle/upstream/projects/unix/Makefile
mupen64plus-rsp-hle/upstream/src/hle_external.h
mupen64plus-rsp-hle/upstream/src/plugin.c

mupen64plus/mupen64plus-rsp-hle@7ea802e

rsp-hle: Update to commit 7ea802e.

---

mupen64plus-ui-console/upstream/projects/VisualStudio2017/mupen64plus-ui-console.sln
mupen64plus-ui-console/upstream/projects/VisualStudio2017/mupen64plus-ui-console.vcxproj
mupen64plus-ui-console/upstream/src/debugger.c

mupen64plus/mupen64plus-ui-console@5ec0b2a

ui-console: Update to commit 5ec0b2a.

---

mupen64plus-video-rice/upstream/projects/VisualStudio2017/mupen64plus-video-rice.vcxproj
mupen64plus-video-rice/upstream/src/OGLExtensions.cpp
mupen64plus-video-rice/upstream/src/Render.cpp
mupen64plus-video-rice/upstream/src/TextureFilters_2xsai.cpp
mupen64plus-video-rice/upstream/src/TextureFilters_hq2x.cpp
mupen64plus-video-rice/upstream/src/osal_opengl.h

https://github.com/mupen64plus/mupen64plus-video-rice/commit/71fc6d7

video-rice: Update to commit 71fc6d7.

---

mupen64plus-video-gliden64/upstream/README.md
mupen64plus-video-gliden64/upstream/appveyor.yml
mupen64plus-video-gliden64/upstream/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp
mupen64plus-video-gliden64/upstream/src/Graphics/OpenGLContext/GLSL/glsl_ShaderStorage.h

video-gliden64: Update to commit 517723d.

---

build_common/version_common.gradle

Add ndkVersion because ANDROID_NDK_HOME will be deprecated in future releases.

Add ndkVersion

---

.github/workflows/continuous-integration-workflow.yml

This reduces the Install step from almost 2 minutes to 16 seconds.

Removed ndk-bundle and change environment variable

---

.github/ISSUE_TEMPLATE/bug-report.yml

Small update the label was not working.

Update bug report

---

.github/workflows/continuous-integration-workflow.yml

Fix Github Workflow artifact name

---

.github/workflows/build.yml

Hi @fzurita I've added Pre-release to the releases section, this will be updated and overwritten everytime a new PR to master is performed. I've added this because the Nightly builds will expire after some time:
The Pre-release will look like the picture below:

Add Pre-Release

---

app/src/main/java/paulscode/android/mupen64plusae/GalleryActivity.java
app/src/main/java/paulscode/android/mupen64plusae/dialog/LocaleDialog.java
app/src/main/java/paulscode/android/mupen64plusae/dialog/Popups.java
app/src/main/java/paulscode/android/mupen64plusae/persistent/GlobalPrefs.java

Addressing issue #1017 by extending Popups with DialogFragment and making LocaleDialog class to retain the fragments. I'm unsure what the problem is with the last two examples in the issue (ManageControllerProfilesActivity & ManageEmulationProfilesActivity) so I haven't addressed them with this pull request

Popups extending DialogFragment

---

.github/workflows/build.yml
miniupnp-bridge/CMakeLists.txt
miniupnp-bridge/build.gradle
mupen64plus-audio-android/CMakeLists.txt
mupen64plus-audio-android/build.gradle
mupen64plus-rsp-parallel/build.gradle
mupen64plus-rsp-parallel/upstream/CMakeLists.txt
mupen64plus-rsp-parallel/upstream/win32/mman/sys/CMakeLists.txt
mupen64plus-video-angrylion-plus/build.gradle
mupen64plus-video-angrylion-plus/upstream/CMakeLists.txt
mupen64plus-video-gliden64/build.gradle
mupen64plus-video-gliden64/upstream/src/CMakeLists.txt
mupen64plus-video-gliden64/upstream/src/GLideNHQ/CMakeLists.txt
mupen64plus-video-gliden64/upstream/src/osal/CMakeLists.txt
mupen64plus-video-parallel/build.gradle
mupen64plus-video-parallel/upstream/CMakeLists.txt
ndkLibs/libnatpmp/CMakeLists.txt
ndkLibs/miniupnp/miniupnpc/CMakeLists.txt
ndkLibs/png/CMakeLists.txt

@fzurita the best wishes for the new year, I've optimized the workflow and updated Cmake to version 3.22.1.

Optimize Github workflow and update Cmake to version 3.22.1

---

app/src/main/java/paulscode/android/mupen64plusae/input/TouchController.java
app/src/main/java/paulscode/android/mupen64plusae/input/map/TouchMap.java
mupen64plus-input-android/src/plugin.cpp

This should tidy up everything from the recent changes.

Fix signs, zero TouchMap deadzone, and cleanup

---

.github/workflows/build.yml

Hi @fzurita this fixes another pipeline run warning.

Fix action warning

---

.github/workflows/build.yml
README.md

Hi @fzurita, I have added download button to README.md
It will look like this:

Added download button to README.md
